---
- hosts: localhost
  connection: local

  tasks:
    - name: "brew install alot"
      homebrew: name={{ item }} state=present
      with_items:
       - vim
       - awscli
       - lua
       - ncdu
       - mutt
       - openssl
       - tmux
       - htop
       - bash
       - bash-completion
       - geoip
       - lftp
       - links
       - nmap

    - name: "brew cask install spotify,iterm2"
      homebrew_cask: name={{ item }} state=present
      with_items:
       - spotify
       - iterm2
       - virtualbox
       - vagrant
       - vlc 
